### ISSUE TITLE
文档是否需要区分 gc 版本？

### ISSUE THREAD

**Issue by arub3do** [GenKitCN/gcdoc#7]
如果默认是跟踪 dev 版本，`config.json` 的内容就不一定靠谱了。

**Comment by Wansn-w** [comment]
抱歉啊，因为个人原因迟迟没更新config.json的配置释义.... ~~主要是当时刚写完就大概config.json~~ 呜呜呜

**Comment by Wansn-w** [comment]
不出意外的话下午就更

**Comment by TomyJan** [comment]
config现在已经有版本标记,目前版本 v4
